<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../config/db.php'; require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/question_bank_blueprint.php'; requireAuth(); $pdo=getDBConnection();
try{
 $in=json_decode(file_get_contents('php://input'),true)?:[]; $course=strtoupper(trim((string)($in['paper_code']??''))); $sem=trim((string)($in['semester']??'')); $year=trim((string)($in['academic_year']??'')); $exam=trim((string)($in['exam_type']??'')); $qs=$in['questions']??[]; if($course==='')throw new RuntimeException('Course code is required.');
 $st=$pdo->prepare("SELECT * FROM question_bank_blueprints WHERE status='PUBLISHED' AND qbb_enabled=1 AND UPPER(paper_code)=UPPER(?) AND (semester=? OR semester IS NULL OR semester='') AND (academic_year=? OR academic_year IS NULL OR academic_year='') AND (exam_type=? OR exam_type IS NULL OR exam_type='') ORDER BY published_at DESC,id DESC LIMIT 1"); $st->execute([$course,$sem,$year,$exam]); $bp=$st->fetch(PDO::FETCH_ASSOC);
 if(!$bp){echo json_encode(['success'=>true,'enabled'=>false,'found'=>false,'valid'=>true,'message'=>'Use Question Bank Blueprint is OFF for this course.']);exit;}
 $matrix=json_decode((string)$bp['matrix_json'],true);if(!is_array($matrix))$matrix=[]; $sub=[];$unit=[]; foreach($qs as $q){$u=(int)($q['unit_no']??$q['unit']??0);$su=trim((string)($q['sub_unit']??$q['subunit']??($u.'.1')));$unit[$u]=($unit[$u]??0)+1;$sub[$su]=($sub[$su]??0)+1;}
 $reqSub=[];$reqUnit=[];$rows=[];$errors=[]; foreach($matrix as $i=>$r){$u=(int)($r['unit']??0);$su=(string)($r['sub_unit']??'');$need=(int)($r['required_count']??0);$reqSub[$su]=($reqSub[$su]??0)+$need;$reqUnit[$u]=($reqUnit[$u]??0)+$need;$a=(int)($sub[$su]??0);$au=(int)($unit[$u]??0);$rows[]=['row_no'=>$i+1,'unit'=>$u,'sub_unit'=>$su,'section'=>(string)($r['section']??''),'k_level'=>(string)($r['k_level']??''),'co_level'=>'CO'.preg_replace('/\D/','',(string)($r['k_level']??'K1')),'marks'=>(int)($r['marks']??0),'question_type'=>(string)($r['question_type']??''),'required_count'=>$need,'available_subunit'=>$a,'available_unit'=>$au];}
 foreach($reqSub as $su=>$n){$a=(int)($sub[$su]??0);if($a<$n)$errors[]="Sub-Unit {$su}: blueprint requires {$n} questions, but the uploaded bank totally contains only {$a}.";} foreach($reqUnit as $u=>$n){$a=(int)($unit[$u]??0);if($a<$n)$errors[]="Unit {$u}: blueprint requires {$n} questions, but the uploaded bank totally contains only {$a}.";}
 echo json_encode(['success'=>true,'enabled'=>true,'found'=>true,'valid'=>!$errors,'blueprint_id'=>(int)$bp['id'],'rows'=>$rows,'units'=>$unit,'sub_units'=>$sub,'errors'=>array_values(array_unique($errors)),'total_uploaded'=>count($qs)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
}catch(Throwable $e){http_response_code(400);echo json_encode(['success'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}
