<?php
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/config.php'; require_once __DIR__.'/../config/db.php'; require_once __DIR__.'/../includes/auth.php'; require_once __DIR__.'/../includes/question_bank_blueprint.php'; requireAuth(); $pdo=getDBConnection();
try {
$in=json_decode(file_get_contents('php://input'),true)?:[]; $course=strtoupper(trim((string)($in['paper_code']??''))); $sem=trim((string)($in['semester']??'')); $year=trim((string)($in['academic_year']??'')); $exam=trim((string)($in['exam_type']??'')); $qs=is_array($in['questions']??null)?$in['questions']:[]; if($course==='') throw new RuntimeException('Course code is required.');
$st=$pdo->prepare("SELECT * FROM question_bank_blueprints WHERE status='PUBLISHED' AND qbb_enabled=1 AND UPPER(paper_code)=UPPER(?) AND (semester=? OR semester IS NULL OR semester='') AND (academic_year=? OR academic_year IS NULL OR academic_year='') AND (exam_type=? OR exam_type IS NULL OR exam_type='') ORDER BY published_at DESC,id DESC LIMIT 1"); $st->execute([$course,$sem,$year,$exam]); $bp=$st->fetch(PDO::FETCH_ASSOC);
if(!$bp){echo json_encode(['success'=>true,'enabled'=>false,'found'=>false,'valid'=>true,'message'=>'Use Question Bank Blueprint is OFF for this course.']);exit;}
$matrix=json_decode((string)$bp['matrix_json'],true); if(!is_array($matrix))$matrix=[];
$sec=function($v){$v=strtoupper(trim((string)$v)); if(preg_match('/SECTION[- ]?([A-D])$/',$v,$m))$v=$m[1]; return $v;}; $norm=function($v){return strtoupper(trim((string)$v));}; $co=function($v){$v=$norm($v); return preg_match('/^CO[0-9]+$/',$v)?$v:'CO1';};
$exact=[];$sub=[];$unit=[]; foreach($qs as $q){$u=preg_match('/[1-5]/',(string)($q['unit_no']??$q['unit']??''),$m)?$m[0]:''; $su=trim((string)($q['sub_unit']??$q['subunit']??'')); $key=implode('|',[$u,$su,$sec($q['section_type']??$q['section']??''),$norm($q['question_type']??$q['type']??''),$norm($q['k_level']??$q['k']??''),$co($q['co_level']??$q['co']??''),(int)($q['marks']??0)]); $exact[$key][]= (string)($q['q_number']??$q['question_no']??''); if($su!=='')$sub[$su]=($sub[$su]??0)+1; if($u!=='')$unit[$u]=($unit[$u]??0)+1;}
$rows=[];$errors=[];$reqSub=[];$reqUnit=[]; foreach($matrix as $i=>$r){$u=(string)($r['unit']??'');$su=trim((string)($r['sub_unit']??''));$se=$sec($r['section']??'');$ty=$norm($r['question_type']??'');$k=$norm($r['k_level']??'K1');$c=$co($r['co_level']??'CO1');$ma=(int)($r['marks']??0);$need=(int)($r['required_count']??0);$key=implode('|',[$u,$su,$se,$ty,$k,$c,$ma]);$matches=$exact[$key]??[];$a=count($matches);$reqSub[$su]=($reqSub[$su]??0)+$need;$reqUnit[$u]=($reqUnit[$u]??0)+$need;$rows[]=['row_no'=>$i+1,'unit'=>$u,'sub_unit'=>$su,'section'=>$se,'k_level'=>$k,'co_level'=>$c,'marks'=>$ma,'question_type'=>$ty,'required_count'=>$need,'exact_count'=>$a,'available_subunit'=>(int)($sub[$su]??0),'available_unit'=>(int)($unit[$u]??0),'matched_question_numbers'=>$matches]; if($a<$need)$errors[]="{$su} / {$se} / {$ty} / {$k} / {$c} / {$ma} mark(s): blueprint requires {$need}, but the uploaded question bank contains only {$a} matching question(s).";}
foreach($reqSub as $su=>$need){$a=(int)($sub[$su]??0);if($a<$need)$errors[]="Sub-Unit {$su}: blueprint requires {$need} questions, but the uploaded question bank totally contains only {$a}.";} foreach($reqUnit as $u=>$need){$a=(int)($unit[$u]??0);if($a<$need)$errors[]="Unit {$u}: blueprint requires {$need} questions, but Unit {$u} totally contains only {$a}.";}
echo json_encode(['success'=>true,'enabled'=>true,'found'=>true,'valid'=>!$errors,'blueprint_id'=>(int)$bp['id'],'rows'=>$rows,'units'=>$unit,'sub_units'=>$sub,'errors'=>array_values(array_unique($errors)),'total_uploaded'=>count($qs)],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
} catch(Throwable $e){http_response_code(400);echo json_encode(['success'=>false,'message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}
